name: monethy
description: A Personal Finance Tracker built with Flutter.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fl_chart: ^0.65.0
  http: ^1.2.0
  connectivity_plus: ^6.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  uuid: ^4.2.1
  intl: ^0.19.0
  google_fonts: ^5.0.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  flutter_dotenv: ^5.0.2
  google_sign_in: ^7.2.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/logo/app_icon.png
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/app_icon.png"
